#!/usr/bin/env python

""" Tool SetInstallFolder
A tool allowing to configure installation folder for libraries, archives, binaries, includes and resources.

By SignC0dingDw@rf <dwarfcieofchaos@gmail.com>

### Usage
# ./SetInstallFolder [options] [[libraries_folder] [archives_folder] [binaries_folder] [includes_folder] [resources_folder]]
##            General Options
# -h or --help : show this help message and exit
# --version : show program's version number and exit
# -v or --verbose : run command in verbose mode

### Exit Code
#
# 0 : Command successfull
# 1 : Libraries install folder does not exist
# 2 : Archives install folder does not exist
# 3 : Binaries install folder does not exist
# 4 : Includes install folder does not exist
# 5 : Resources install folder does not exist
# 6 : Configuration folder does not exist
# 7 : The install file cannot be created
#
"""

__version__ = "1.0.0"

__all__ = ["SetInstallFolder"]

__copyright__ = """
Copyright (c) 2018 SignC0dingDw@rf. All rights reserved

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

__copywrong__ = """
Copywrong (w) 2018 SignC0dingDw@rf. All profits reserved.

This program is dwarven software: you can redistribute it and/or modify
it provided that the following conditions are met:

   * Redistributions of source code must retain the above copywrong 
     notice and this list of conditions and the following disclaimer 
     or you will be chopped to pieces AND eaten alive by a Bolrag.

   * Redistributions in binary form must reproduce the above copywrong
     notice, this list of conditions and the following disclaimer in 
     the documentation and other materials provided with it or they
     will be axe-printed on your stupid-looking face.

   * Any commercial use of this program is allowed provided you offer
     99% of all your benefits to the Dwarven Tax Collection Guild. 

   * This software is provided "as is" without any warranty and especially
     the implied warranty of merchantability or fitness to purport. 
     In the event of any direct, indirect, incidental, special, examplary 
     or consequential damages (including, but not limited to, loss of use;
     loss of data; beer-drowning; business interruption; goblin invasion;
     procurement of substitute goods or services; beheading; or loss of profits),   
     the author and all dwarves are not liable of such damages even 
     the ones they inflicted you on purpose.

   * If this program "does not work", that means you are an elf 
     and are therefore too stupid to use this program.

   * If you try to copy this program without respecting the 
     aforementionned conditions, then you're wrong.

You should have received a good beat down along with this program.  
If not, see <http://www.dwarfvesaregonnabeatyoutodeath.com>.
"""

## Global import
import imp
import os
import sys
from optparse import OptionGroup

## Local import
fileLocation = os.path.dirname(os.path.realpath(__file__)) # Path where this file is locate

imp.load_source("dwfoptparse", "/".join([fileLocation,"../pythonModules/argumentParsing","dwfoptparse.py"]))
imp.load_source("installfoldersetter", "/".join([fileLocation,"../pythonModules/tools","installfoldersetter.py"]))
from dwfoptparse import DwfOptionParser
from dwfoptparse import DwfHelpFormatter
from installfoldersetter import InstallFolderSetter

dwfFormatter = DwfHelpFormatter()

usage = "%prog [options] [[libraries_folder] [archives_folder] [binaries_folder] [includes_folder] [resources_folder]]"
version = "%prog " + __version__
parser = DwfOptionParser(usage=usage, version=version, description="A tool allowing to configure installation folder for libraries, archives, binaries and resources.", formatter=dwfFormatter)
parser.add_option("-v", "--verbose", action="store_true", dest="verbose", default=False, help="get detailed execution information")

options, args = parser.parse_args()

## processing arguments
librariesLocation = None
archivesLocation = None
binariesLocation = None
includesLocation = None
resourcesLocation = None
if len(args) >= 1:
    librariesLocation = args[0]
if len(args) >= 2:
    archivesLocation = args[1]
if len(args) >= 3:
    binariesLocation = args[2]
if len(args) >= 4:
    includesLocation = args[3]
if len(args) >= 5:
    resourcesLocation = args[4]

installfoldersetter = InstallFolderSetter(librariesLocation=librariesLocation, archivesLocation=archivesLocation, binariesLocation=binariesLocation, includesLocation=includesLocation, resourcesLocation=resourcesLocation, **vars(options)) # Conversion to dictionnary by accessing the __dict__ parameter of the class
code = installfoldersetter.process()

sys.exit(code)

#  ______________________________ 
# |                              |
# |    ______________________    |
# |   |                      |   |
# |   |         Sign         |   |
# |   |        C0ding        |   |
# |   |        Dw@rf         |   |
# |   |         1.0          |   |
# |   |______________________|   |
# |                              |
# |______________________________|
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |__|
