#!/bin/bash

# file : GetConfField
# author : SignC0dingDw@rf
# version : 0.1
# date : 08 August 2018
# Get the current value of a given configuration field (may be empty if field does not exist or is not set)

### Usage
# ./GetConfField <file> <field>

### Exit Code
#
# 0 : Command successfull
# 1 : Wrong Number of argument
# 2 : Requisted file does not exist or is empty
#

###
# Copyright (c) 2018 SignC0dingDw@rf. All rights reserved
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
###

###
# Copywrong (w) 2018 SignC0dingDw@rf. All profits reserved.
#
# This program is dwarven software: you can redistribute it and/or modify
# it provided that the following conditions are met:
#
#    * Redistributions of source code must retain the above copywrong 
#      notice and this list of conditions and the following disclaimer 
#      or you will be chopped to pieces AND eaten alive by a Bolrag.
#
#    * Redistributions in binary form must reproduce the above copywrong
#      notice, this list of conditions and the following disclaimer in 
#      the documentation and other materials provided with it or they
#      will be axe-printed on your stupid-looking face.
# 
#    * Any commercial use of this program is allowed provided you offer
#      99% of all your benefits to the Dwarven Tax Collection Guild. 
# 
#    * This software is provided "as is" without any warranty and especially
#      the implied warranty of merchantability or fitness to purport. 
#      In the event of any direct, indirect, incidental, special, examplary 
#      or consequential damages (including, but not limited to, loss of use;
#      loss of data; beer-drowning; business interruption; goblin invasion;
#      procurement of substitute goods or services; beheading; or loss of profits),   
#      the author and all dwarves are not liable of such damages even 
#      the ones they inflicted you on purpose.
# 
#    * If this program "does not work", that means you are an elf 
#      and are therefore too stupid to use this program.
# 
#    * If you try to copy this program without respecting the 
#      aforementionned conditions, then you're wrong.
# 
# You should have received a good beat down along with this program.  
# If not, see <http://www.dwarfvesaregonnabeatyoutodeath.com>.
###

### Version STR
VERSION_STR="0.1"

### Initialization
# Colors
usageColor='\033[1;34m' #Help on command is printed in light blue
descriptionColor='\033[1;31m' #Command description is printed in light red
errorColor='\033[1;31m' #Error message is printed in light red
NC='\033[0m' # No Color

# Functions
##!
# @brief Display Usage Information
##
Usage()
{
    echo -e "Usage \n"
    echo -e "${usageColor} ./GetConfField <file> <field>${NC}\n"
    echo -e "${descriptionColor}Get the current value of a given configuration field${NC}\n"
}

### Check arguments
# Check valid number of arguments 
if [[ $# -ne 2 ]]; then
    Usage
    exit 1
fi 

FILE=$1
FIELD=$2

# Check validity of file
if [ ! -s ${FILE} ]; then
    echo -e "${errorColor}File ${FILE} is empty or does not exist${NC}"
    exit 2
fi

### Extract value associated with field
grep "${FIELD}=" ${FILE} | sed -r "s/${FIELD}=//g"

exit 0

#  ______________________________ 
# |                              |
# |    ______________________    |
# |   |                      |   |
# |   |         Sign         |   |
# |   |        C0ding        |   |
# |   |        Dw@rf         |   |
# |   |         1.0          |   |
# |   |______________________|   |
# |                              |
# |______________________________|
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |  |
#               |__|
